FROM python:3.13-slim-bookworm

LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="Obsidian Daylio Parser"
LABEL org.label-schema.description="Convert .csv Daylio backup into markdown notes."
LABEL org.label-schema.url="https://github.com/DeutscheGabanna/Obsidian-Daylio-Parser/"

WORKDIR /app
COPY tests/  .
RUN pip install obsidian-daylio-parser

ENTRYPOINT ["obsidian-daylio-parser"]
CMD ["--help"]