name: Auto-generate PR Description

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate pull request description
      uses: octue/generate-pull-request-description@1.0.0.beta-2
      id: pr-description
      with:
        pull_request_url: ${{ github.event.pull_request.url }}
        api_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update pull request body
      uses: riskledger/update-pr-description@v2
      with:
        body: ${{ steps.pr-description.outputs.pull_request_description }}
        token: ${{ secrets.GITHUB_TOKEN }}