name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        find . -name '*.py' -exec pylint {} --fail-under=8 \;
        pylint_exit_code=$?
        if [ $pylint_exit_code -ne 0 ]; then
          echo "Pylint check failed with exit code $pylint_exit_code"
          exit $pylint_exit_code
        fi