name: Pylint
on: [ pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - uses: pr-annotators/pylint-pr-annotator@main
      - name: Analysing the code with pylint
        run: pylint $(git ls-files '*.py')