name: Test
on: [ pull_request ]
jobs:
  test:
    strategy:
      matrix:
        # https://devguide.python.org/versions/
        python: [ 3.11, 3.12 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Discover tests
        run: python -m unittest discover -s ./_tests
